school/classroom/urls.py
from django.urls import path
from . import views
app_name = 'classroom'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('contact/', views.ContactFormView.as_view(), name='contact_form'),
    path('teacher/', views.TeacherCreateView.as_view(), name='create_teacher'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('teacher_list/', views.TeacherListView.as_view(), name='teacher_list'),
    path('teacher_detail/<int:pk>', views.TeacherDetailView.as_view(), name='detail_teacher'),
    path('update_teacher/<int:pk>', views.TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>', views.TeacherDeleteView.as_view(), name='delete_teacher'),
]

school/school/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls')),
]

school/classroom/models.py
from django.db import models

# Create your models here.

class teacher (models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

school/classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView,UpdateView, DeleteView
from classroom.models import teacher
from classroom.forms import ContactForm
from django.urls import reverse_lazy

def home_view(request):
    return render(request, 'classroom/home.html')

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    success_url = reverse_lazy('classroom:thanks')

    def form_valid(self, form):
        print(form.cleaned_data["name"])
        return super().form_valid(form)

class ThanksPage(TemplateView):
    template_name = 'classroom/thanks.html'

class TeacherCreateView(CreateView):
    model = teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:home')

    def form_valid(self, form):
        print(form.cleaned_data["first_name"])
        return super().form_valid(form)

class TeacherListView(ListView):
    model = teacher
    queryset = teacher.objects.all()
    context_object_name = 'teacher_list'
    template_name = 'classroom/teacher_list.html'

class TeacherDetailView(DetailView):
    model = teacher
    
 
class TeacherUpdateView(UpdateView):
    model = teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:home')


class TeacherDeleteView(DeleteView):
    model = teacher
    success_url = reverse_lazy('classroom:teacher_list')

school/classroom/templates/classroom/contact.html
<h1>hallo ich bin Juan Pablo </h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>


<a href="/ ">BACK TO HOME</a>

school/classroom/templates/classroom/home.html
<h1> welcome to my page</h1>


<ul>
    <li>
        <a href="{% url 'classroom:thanks' %}">THANK YOU FOR YOUR TIME</a>
    </li>

    <li>
        <a href="{% url 'classroom:contact_form' %}">CONTACT FORM PAGE LINK</a>
    </li>

    <li>

        <a href="{% url 'classroom:create_teacher' %}">TEACHER FORM PAGE LINK</a>

    </li>

    <li>

        <a href="{% url 'classroom:teacher_list' %}">TEACHER LIST PAGE LINK</a>
    </li>

</ul>
    

school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete this teacher?</h1>
<h2> {{teacher}}</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete."/>
</form>

school/classroom/templates/classroom/teacher_detail.html
<h1>Details for a teacher</h1>
{{teacher}}


<a href="/ ">BACK TO HOME</a>

school/classroom/templates/classroom/teacher_form.html
<h1>TeacherForm</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

<a href="/ ">BACK TO HOME</a>

school/classroom/templates/classroom/teacher_list.html
<h1>list of teacher (listview)</h1>
<ul>
    {% for teacher in teacher_list %}
    <li><a href="/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
    <ul>
        <li>
            <a href="/update_teacher/{{teacher.id}}">update information for {{teacher.first_name}} </a>
        <li>
            <a href="/delete_teacher/{{teacher.id}}">DELETE {{teacher.first_name}} </a>
        </li>
        </li>
    </ul>
    {% endfor %}
</ul>

<a href="/ ">BACK TO HOME</a>

school/classroom/templates/classroom/thanks.html
<h1> Hallo ich bin Juan Pablo Gonzalez Trejos</h1>


<a href="/ ">BACK TO HOME</a>