my_card/card/urls.py
from django.urls import path
from . import views

app_name = 'card'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
    path('', views.acerca, name='acerca')
]

my_card/my_card/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('card.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_card/card/models.py
from django.db import models
class Card(models.Model):
    # Campos del modelo
    name = models.CharField(max_length=30)
    email = models.EmailField()
    mensaje = models.CharField(max_length=800)

    def __str__(self):
        return f"datos de la persona: {self.name}  {self.email} {self.mensaje}"

my_card/card/views.py
from django.shortcuts import render, redirect
from . import models
from .models import Card

def list(request):
    all_cards = models.Card.objects.all()

    # Anonimizar los correos electrónicos
    for card in all_cards:
        card.email = card.email[:3] + '...' + card.email.split('@')[-1]

    context = {'all_cards': all_cards}
    return render(request, 'card/list.html', context=context)


def add(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        mensaje = request.POST['mensaje']
        
        new_card = Card(name=name, email=email, mensaje=mensaje)
        new_card.save()
        
        return redirect('card:list')
    else:
        return render(request, 'card/add.html')


def delete(request):
    if request.method == 'POST':
        pk=request.POST['pk']
        try:
           models.Card.objects.get(pk=pk).delete()
           return render(request, 'card/delete.html')
        except:
            print("Error")
            return redirect('card:list')
    else:
        return render(request, 'card/delete.html')
    
def acerca(request):
    return render(request, 'card/acerca.html')
    

my_card/card/templates/card/acerca.html
{% extends 'acerca.html' %}
{% load static %}
   
{% block content %}
<br>
<br>
    <img class="rounded-image" src="{% static 'my_app/me.jpg' %}" alt="Juan Pablo" width="300" height="300">
{% endblock %}

my_card/card/templates/card/add.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br>
<br>
<div class="container">
    <img class="rounded-image" src="{% static 'my_app/me.jpg' %}" alt="Juan Pablo" width="150" height="150">
    <p>
        I'm a university student, currently studying tenth semester of systems engineering and computing (2025), 
        at the Technological University of Pereira-Colombia.
    </p>
    <h1>Send a message</h1>
    <form action="" method='POST'>
    
        {% csrf_token %}

        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
        </div>
    
        <div class="form-group">
            <label for="mensaje">message</label>
            <textarea class="form-control" id="mensaje" name="mensaje" placeholder="menssage"></textarea>
          </div>
          
        <div>
        <br>
        <input class="btn btn-primary" type="submit" value="Send"> 
        </div>
    </form>
</div>
{% endblock %}

my_card/card/templates/card/delete.html
{% extends "base.html"%}
{% block content %}
<div class="container">
    <h1>Enter the primary key of the row you want to delete</h1>
    <div>
    <form action=" " method='POST'>
        {% csrf_token %}
        <div class="form-group">
            <label for="pk">Primary Key: </label>
            <input class="form-control" type="text" name="pk" id="pk">
            <input class="form-control" type="submit" value = "Delete" >
        </div>
    </form>
</div>
{% endblock %}

#Esta vista por el momento esta inactiva pero si se requiere solo es activar un link con el nombre
#de eliminar.

my_card/card/templates/card/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <br>
    <br>
    <h1>Messages</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for card in all_cards %}
            <tr>
                <td>{{ card.name }}</td>
                <td>{{ card.email }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

my_card/templates/acerca.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>JgonzalezT</title>
  <link rel="stylesheet" href="{% static 'my_app/acerca.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body class="my-custom-body">
  <!-- Barra de navegación (navbar) -->
  <nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'card:acerca' %}">JgonzalezT</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>

  <!-- Contenido colapsable de la barra de navegación -->
  <div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
    <div class="bg-dark p-4 static-container">
      <ul class="nav flex-column">
        <li class="nav-item">
          <br>
          <br>
          <a class="nav-link text-white" aria-current="page" href="{% url 'card:add' %}">Message</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-danger" href="https://github.com/juanpablogt" target="_blank">GitHub</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white active" aria-current="page" href="{% url 'card:list' %}">Views</a>
        </li>
      </ul>
    </div>
  </div>

  <!-- Sección principal del contenido -->
  <div class="descripcion">
    {% block content %}
    {% endblock %}
    <br><br>
    <p>Hallo, ich heiße Juan Pablo González, ich komme aus Kolumbien. Derzeit (2025) studiere ich im Zehntel Semester Systemtechnik und Informatik an der Technischen Universität Pereira-Kolumbien.</p>
  </div>

  <hr>

  <!-- Listas de habilidades e intereses -->
  <div class="listas">
    <div class="lis1">
      <h3>Fähigkeiten</h3>
      <ul id="sk">
        <li>Django</li>
        <li>Python</li>
        <li>SQL</li>
        <li>CSS</li>
        <li>Git</li>
      </ul>
    </div>
    
    <div class="lis2">
      <h3>Berufliche Interessen</h3>
      <ul id="intereses">
        <li>Webentwicklung</li>
        <li>Künstliche Intelligenz</li>
        <li>Datenwissenschaft</li>
      </ul>
    </div>
  </div>

  <!-- Tabla de contactos -->
  <div class="contact">
    <table border="1">
      <thead>
        <tr>
          <th colspan="4">
            <h3>Kontakt</h3>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="https://instagram.com/jpablo91091/" target="_blank"><img src="https://img.shields.io/badge/-Instagram-%23E4405F?style=for-the-badge&logo=instagram&logoColor=white" target="_blank"></a></td>
          <td><a href="https://www.linkedin.com/in/juan-pablo-gonzalez-trejos-90025b337/" target="_blank"><img src="https://img.shields.io/badge/-Linkedin-%230077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank"></a></td>
          <td><a href="https://www.facebook.com/juapabgonzalez/" target="_blank"><img src="https://img.shields.io/badge/-Facebook-%231877F2?style=for-the-badge&logo=facebook&logoColor=white" target="_blank"></a></td>
        </tr>
      </tbody>
    </table>
  </div>
</body>
</html>

my_card/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <meta charset="UTF-8">
  <title>JgonzalezT</title>
  <link rel="stylesheet" href="{% static 'my_app/add.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

</head>

<body class="my-custom-body">
  <div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
    <div class="bg-dark p-4 static-container">
        <ul class="nav flex-column">
                <li class="nav-item">
            <br>
            <br>
                    <a class="nav-link text-white" href="{%url 'card:add'%}">Mensaje</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="https://github.com/juanpablogt" target="_blank">GitHub</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white " aria-current="page" href="{%url 'card:list'%}">Visitas</a>
            </li>
            </ul>
      </div>
    </div>
<nav class="navbar navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'card:acerca'%}">JgonzalezT</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</nav>
    {%block content%}
    {%endblock%}

</body>
</html>