my_site/my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'

urlpatterns = [
    path('', views.simple_view, name='home'),
    path('contact/', views.contact_view, name='contact'),
    path('ensayo/', views.ensayo_view, name='ensayo')
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.http.response import HttpResponse
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('', views.home_view, name='home')
    
]

handler404 = 'my_site.views.my_custom_page_error_view'

my_site/my_app/models.py
from django.db import models

# Create your models here.

class patient (models.Model):
    email = models.EmailField(max_length=254)
    message = models.CharField(max_length=500)


    

my_site/my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

def simple_view(request):
    return render(request,'first_app/maqueta.html')

def contact_view(request):
    
    my_var = {'first_name':'pablo','last_name':'gonzalez', 'age':'32', 'list':[1,2,3,4,5], 
              'user_logged_in':True}
    return render(request,'first_app/contact.html',context= my_var)

def ensayo_view(request):
    return render(request,'first_app/ensayo.html')

my_site/my_site/views.py
from django.http.response import HttpResponse
from . import views
from django.urls import path
from django.urls.conf import include
from django.shortcuts import render


# Create your views here.
def home_view(request):
    return HttpResponse("<h1> hallo Ich bin Juan Pablo Gonzalez Trejos</h1>")

def my_custom_page_error_view(request, exception):
    return render(request, 'Error.html', status=404)

my_site/my_app/templates/first_app/contact.html
<html>

    <head>
        <title>J.Pablo Gonzalez</title>
        <link rel="stylesheet" type="text/css" href="first_app/styles.css">
    </head>

    <body>
        
        <div class="descripcion">
            <h1>J.Pablo Gonzalez</h1>

            <h2>mi segundo nombre es: {{first_name | capfirst}}</h2>
            <h2>mi apellido es: {{last_name | capfirst}}</h2>
            <h2>mi edad es: {{age}}</h2>

            <h2>{% if user_logged_in %} 
                    <h3>Bienvenido {{first_name | capfirst}}</h3> 
                    {% else %} 
                    <h3>Por favor inicia sesion</h3>
                {% endif %}
            </h2>

            <ul>
            {% for num in list %}
            {% if num == 1 %}
                <li>El numero es: {{num}}</li>
            {% else %}
                <li>{{num}}</li>

            {% endif %}
            {% endfor %}

            </ul>
         
            <h1><a href="{% url 'my_app:home' %}">Home</a></h1>

        </div>

    </body>

</html>

my_site/my_app/templates/first_app/ensayo.html
{% extends 'base.html' %}
{% load static %}
   
{% block content %}
    <img src="{% static 'my_app/me.jpg' %}" alt="Juan Pablo" width="600" height="600">
{% endblock %}

my_site/my_app/templates/first_app/maqueta.html
{% extends 'base.html' %}
{% load static %}
   
{% block content %}
    <img src="{% static 'my_app/me.jpg' %}" alt="Juan Pablo" width="500" height="600">
{% endblock %}